% Use this script to compute the frequencies in Hz that are generated by the DAC inside the suchai 1 RC experiment
fcutoff = 92;
fmin = fcutoff*0.1;
fmax = fcutoff*10;

cmdValues = [6793 4029 2389 1417 840 498 295 175 104 61 36 21 13 7 4];
oversamplingCoeff = 4;
fcomputed = zeros(size(cmdValues));

for i = 1 : length(fcomputed)
    fcomputed(i) = computeFreqSignalHz(cmdValues(i), oversamplingCoeff);
end
fcomputed_log10 = log10(fcomputed);

loglog(fcomputed, cmdValues, '*');
hold on;
y1=get(gca,'ylim');
hold on
xPosMin = fmin;
xPosMax = fmax;
xCutoff = fcutoff;
plot([xPosMin xPosMin],y1);
plot([xPosMax xPosMax],y1);
plot([xCutoff xCutoff],y1);
grid on;
title('Command Values for RC Payload to be sent from Ground Station');
xlabel('Frequency [Hz]');
ylabel('Payload Command Value [uint16]');
legend('cmdValues' ,'0.1 \cdot f_{RC}', '10 \cdot f_{RC}', 'f_{RC}');
